export const customLabels = {
    //constants > competitions.js
    const_competitions_222: "2x2x2 Cube",
	const_competitions_333: "3x3x3 Cube",
	const_competitions_444: "4x4x4 Cube",
	const_competitions_555: "5x5x5 Cube",
	const_competitions_666: "6x6x6 Cube",
	const_competitions_777: "7x7x7 Cube",
	const_competitions_333bf: "3x3x3 Blindfolded",
	const_competitions_333oh: "3x3x3 One-Handed",
	const_competitions_clock: "Clock",
    const_competitions_minx: "Megaminx",
    const_competitions_pyram: "Pyraminx",
    const_competitions_skewb: "Skewb",
	const_competitions_sq1: "Square-1",
	const_competitions_333fm: "3x3x3 Fewest Moves",
    const_competitions_444bf: "4x4x4 Blindfolded",
    const_competitions_555bf: "5x5x5 Blindfolded",
    const_competitions_333mbf: "3x3x3 Multi-Blind",
    //constants > registerValidationSchema.js
    const_registerValidationSchema_emailNiepoprawny: "Wrong e-mail",
    const_registerValidationSchema_emailWymagany: "E-mail required",
    const_registerValidationSchema_podajPanstwo: "Select country",
    const_registerValidationSchema_minLiczbaZnakow: "Minimum 8 characters needed",
    const_registerValidationSchema_hasloWymagane: "Password required",
    const_registerValidationSchema_akceptujRegulamin: "Accept terms and conditions",
    //constants > resetPasswordValidationSchema.js
    const_resetPasswordValidationSchema_minLiczbaZnakow: "Minimum 8 characters needed",
    const_resetPasswordValidationSchema_podajNoweHaslo: "Enter a new password",
    const_resetPasswordValidationSchema_noweHasloMusi: "New password must be different",
    const_resetPasswordValidationSchema_haslaMuszaBycIdentyczne: "The passwords must be identical",
    const_resetPasswordValidationSchema_podajStareHaslo: "Enter the old password",
    //constants > userDataValidationSchema.js
    const_userDataValidationSchema_zaKrotkieImie: "Too short name",
    const_userDataValidationSchema_imieWymagane: "Name required",
    const_userDataValidationSchema_imieZawieraNiedozwoloneZnaki: "Name contains characters that are not allowed",
    const_userDataValidationSchema_dataWymagana: "Date required",
    const_userDataValidationSchema_minWiek: "Minimum age: 2 years",
    const_userDataValidationSchema_nieprawidlowy: "Incorrect",
    const_userDataValidationSchema_numerTelefonu: "Enter a phone number",
    const_userDataValidationSchema_nazwiskoWymagane: "Surname required",
    const_userDataValidationSchema_nazwiskoZawieraNiedozZnaki: "Surname contains characters that are not allowed",
    const_userDataValidationSchema_podajPlec: "Enter your gender",
    const_userDataValidationSchema_miastoWymagane: "City required",
    const_userDataValidationSchema_nieprawidlowy2: "Incorrect",
    const_userDataValidationSchema_uzytkownikOTakimWCA: "There is no such user ID at WCA",
    //constants > userProfileEditValidationSchema.js
    const_userProfileEditValidationSchema_podajPanstwo: "Enter the country",
    //components > molecules > Login > LoginButtonsWrapper.js
    login_loginButtonsWrapper_niePamietaszHasla: "Forgot password?",
    //components > molecules > Login > LoginLeftWrapper.js
    login_loginLeftWrapper_nieMaszKonta: "No account?",
    //components > molecules > Register > InputWrapper.js
    register_inputWrapper_mezczyzna: "Male",
    register_inputWrapper_kobieta: "Female",
    register_inputWrapper_inna: "Other",
    //components > molecules > Register > RegisterCompetitions.js -- labelki brać z constants > competitions.js
    //components > molecules > Register > SelectSize.js
    register_selectSize_brak: "None",
    //components > molecules > Results > MenuItemRound.js
    results_menuItemRound_finaly: "Finals",
    results_menuItemRound_polfinaly: "Semifinals",
    results_menuItemRound_rundy: "Rounds",
    //components > molecules > Series > IconsMobileResults.js
    series_iconsMobileResults_bonus: "Extras",
    //components > molecules > Series > SeriesResultsIcon.js -- labelki brać z constants > competitions.js
    //components > molecules > Tournament > PlayerElement.js
    tournament_playerElement_zawodnik: "competitor",
    tournament_playerElement_zawodnik2: "competitor2",
    tournament_playerElement_miejscowosc: "City",
    tournament_playerElement_konkurencje: "events",
    //components > molecules > Tournament > SummaryPlayers.js
    tournament_summaryPlayers_liczbaZawodnikow: "Number of competitors",
    //components > molecules > Tournament > SummaryPlayersCube.js -- labelki brać z constants > competitions.js
    //components > molecules > Tournaments > SeriesButton.js
    tournaments_seriesButton_zawody: "Competitions",
    tournaments_seriesButton_serie: "Series",
    //components > molecules > Tournaments > TournamentsCompetitions.js -- labelki brać z constants > competitions.js
    //components > organisms > Organisms > ChangeLanguage.js
    changeLanguage_changeLanguage_en: "EN",
    //components > organisms > Contact > ContactForm.js
    contact_contactForm_zaKrotkiTytul: "Title too short",
    contact_contactForm_tytulWymagany: "Title required",
    contact_contactForm_emailNiepoprawny: "Email invalid",
    contact_contactForm_emailWymagany: "Email required",
    contact_contactForm_minimum10znakow: "Minimum 10 characters",
    contact_contactForm_wiadomoscWymagana: "Message required",
    contact_contactForm_napisz: "Message us",
    contact_contactForm_emailTitle: "Your e-mail address",
    contact_contactForm_titleTitle: "Title",
    contact_contactForm_napiszWiadomosc: "Write a message",
    contact_contactForm_wyslij: "Send",
    //components > organisms > Contact > LeftWrapper.js
    contact_leftWrapper_zadzwon: "Telephone",
    contact_leftWrapper_dolaczDoSerwera: "JOIN THE SERVER",
    //components > organisms > CookiesPopUp > CookiesPopUp.js
    cookiesPopUp_cookiesPopUp_korzystajacZNaszej: "By using our site, you consent to our use of cookies. You can set conditions for storing or accessing cookies in your browser.",
    //components > organisms > Gallery > GalleryMenu.js
    gallery_galleryMenu_ulubione: "FAVOURITE",
    gallery_galleryMenu_ulubione2: "FAVOURITE",
    gallery_galleryMenu_wybierzZawody: "SELECT COMPETITIONS",
    //components > organisms > Home > HomePageCardContact.js
    home_homePageCardContact_kontakt: "CONTACT",
    //components > organisms > Home > HomePageCardGallery.js
    home_homePageCardGallery_galeria: "GALLERY",
    //components > organisms > Home > HomePageCardTournaments.js
    home_homePageCardTournaments_zawody: "COMPETITIONS",
    //components > organisms > Home > HomePageCardTraining.js
    home_homePageCardTournaments_treningi: "TRAININGS",
    //components > organisms > Login > LoginForm.js
    login_loginForm_niepoprawnyEmail: "Incorrect e-mail",
    login_loginForm_emailWymagany: "E-mail required",
    login_loginForm_zaKrotkieHaslo: "Password too short",
    login_loginForm_hasloWymagane: "Password required",
    login_loginForm_serwerOtrzymal: "The server received an invalid request",
    login_loginForm_uzytkownikJestJuzZalogowany: "The user is already logged in",
    login_loginForm_bladLogowania: "Login error",
    login_loginForm_bladLogowania2: "Login error",
    login_loginForm_zalogujSie: "Sign in",
    login_loginForm_emailPlaceholder: "E-MAIL",
    login_loginForm_passwordPlaceholder: "PASSWORD",
    //components > organisms > LoginLink > LoginLink.js
    loginLink_loginLink_mojeKonto: "MY ACCOUNT",
    loginLink_loginLink_zalogujSie: "SIGN IN",
    //components > organisms > payments > PaymentsPopup.js
    payments_paymentsPopup_zamknij: "CLOSE",
    //components > organisms > register > RegisterForm.js
    register_registerForm_adresieEmail: "e-mail address",
    register_registerForm_uzytkownikOPodanym: "User with",
    register_registerForm_juzIstnieje: "already exists",
    register_registerForm_ograniczenie: "Limit",
    register_registerForm_nieSpelnioneWBazie: "not met in the database",
    register_registerForm_nieznanyBladZapisu: "Unknown database write error",
    register_registerForm_nieznanyBlad: "Unknown error",
    register_registerForm_zarejestrujSie: "SIGN UP",
    register_registerForm_ustawAwatar: "Set up an avatar",
    register_registerForm_zanimPrzesleszZdjecie: "Before you upload a photo",
    register_registerForm_list1: "1. You must be in the photo.",
    register_registerForm_list2: "2. Only one face should be visible in the photo.",
    register_registerForm_list3: "3. Unethical images or offensive content is not allowed.",
    register_registerForm_list4: "4. The photo must follow general netiquette.",
    register_registerForm_list5: "5. An account may be deleted for an incorrect photo.",
    register_registerForm_akceptuje: "Accept",
    register_registerForm_firstnameTitle: "Name",
    register_registerForm_lastnameTitle: "Surname",
    register_registerForm_emailTitle: "E-mail",
    register_registerForm_passwordTitle: "Password",
    register_registerForm_dateTitle: "Date of birth",
    register_registerForm_plecTitle: "Gender",
    register_registerForm_panstwoTitle: "Country",
    register_registerForm_miejscowoscTitle: "City",
    register_registerForm_numertelefonuTitle: "Phone number",
    register_registerForm_wcaidTitle: "WCA ID",
    register_registerForm_wcaidAnnotation: "If you do not have your ID, leave this field blank",
    register_registerForm_ostrzezenie: "Warning! The information provided does not match your WCA account. If you think everything is correct, please continue.",
    register_registerForm_akceptuje2: "Accept",
    register_registerForm_anuluj: "Cancel",
    register_registerForm_ustawSwojeDomyslne: "Set your default events",
    register_registerForm_domyslnyRozmiarKoszulki: "Default T-shirt size",
    register_registerForm_akceptuje3: "*I accept the",
    register_registerForm_regulamin: "terms and conditions",
    register_registerForm_wRegularminieZnajduje: "Please refer to the terms and conditions for the privacy policy, RODO (General Data Protection Regulation) regulations, and site rules.",
    register_registerForm_wyrazamZgodeNa: "I agree to receive the newsletter",
    register_registerForm_bladRejestracji: "Registration error",
    //components > organisms > results > ResultsData.js
    results_resultsData_konkurencja: "Event",
    results_resultsData_runda: "Round",
    results_resultsData_kategoria: "Category",
    //components > organisms > Series > SeriesMenu.js
    series_seriesMenu_serie: "Series",
    //components > organisms > Series > SeriesResults.js
    series_seriesResults_klasyfikacja: "Classification",
    series_seriesResults_wybierzZawodyZListy: "Select a competition from the list to view the classification",
    //components > organisms > Series > SeriesResultsElement.js
    series_seriesResultsElement_bonus: "extras",
    //components > organisms > Series > SeriesResultsElementHeading.js
    series_seriesResultsElementHeading_zawodnik: "Competitor",
    series_seriesResultsElementHeading_bonus: "Extras",
    series_seriesResultsElementHeading_sumaPunktow: "Total score",
    //components > organisms > Series > SeriesResultsMobileElement.js
    series_seriesResultsMobileElement_sumaPunktow: "Total score",
    //components > organisms > Tournament > TournamentInformationContent.js
    tournament_tournamentInformationContent_data: "Date",
    tournament_tournamentInformationContent_miejsce: "City",
    tournament_tournamentInformationContent_konkurencje: "Events",
    tournament_tournamentInformationContent_organizatorzy: "Organizers",
    tournament_tournamentInformationContent_delegaciWca: "WCA Delegates",
    tournament_tournamentInformationContent_limitZawodnikow: "Competitor limit",
    tournament_tournamentInformationContent_brakDanych: "<No data>",
    tournament_tournamentInformationContent_wpisowe: "registration fee",
    tournament_tournamentInformationContent_pln: "PLN",
    tournament_tournamentInformationContent_ostatecznyTerminZawarcia: "Limit date for refunds:",
    tournament_tournamentInformationContent_rejestracja: "Registration",
    tournament_tournamentInformationContent_ostatecznyTerminAkceptowania: "Deadline for accepting competitors from the waiting list:",
    tournament_tournamentInformationContent_ostatecznyTerminZmianyKonkurencji: "Deadline for competitors to update their registered events:",
    //components > organisms > Tournament > TournamentPlayersContent.js
    tournament_tournamentPlayersContent_rejestracjaNaZawody: "Registration for the event has not yet begun. To see the list of competitors, please come back here after registration has started 🙂",
    tournament_tournamentPlayersContent_listaRezerwowa: "RESERVE LIST",
    tournament_tournamentPlayersContent_listaOczekujacych: "WAITING LIST",
    tournament_tournamentPlayersContent_obecnieNieMaZadnego: "There are currently no registered competitors",
    //components > organisms > Tournament > TournamentRegistrationContent.js
    tournament_tournamentRegistrationContent_bladWczytywania: "Loading error",
    tournament_tournamentRegistrationContent_wczytywanie: "Loading...",
    tournament_tournamentRegistrationContent_jestesJuzZarejestrowany: "You are already registered. If you wish to make changes to your registration or cancel it, please go to the tab",
    tournament_tournamentRegistrationContent_mojeKonto: "MY ACCOUNT",
    tournament_tournamentRegistrationContent_imieINazwisko: "Name and surname",
    tournament_tournamentRegistrationContent_plec: "Gender",
    tournament_tournamentRegistrationContent_adresEmail: "E-mail address",
    tournament_tournamentRegistrationContent_wcaID: "WCA ID",
    tournament_tournamentRegistrationContent_dataUrodzenia: "Date of birth",
    tournament_tournamentRegistrationContent_miejscowosc: "City",
    tournament_tournamentRegistrationContent_numerTelefonu: "phone",
    tournament_tournamentRegistrationContent_edytujDane: "EDIT PROFILE",
    tournament_tournamentRegistrationContent_zaznaczConajmniejJednaKonkurencje: "Select at least one competition",
    tournament_tournamentRegistrationContent_akceptujRegulamin: "Accept terms and conditions",
    tournament_tournamentRegistrationContent_wyborKonkurencji: "select events:",
    tournament_tournamentRegistrationContent_rozmiarKoszulkiTitle: "T-shirt size",
    tournament_tournamentRegistrationContent_akceptuje: "Accept",
    tournament_tournamentRegistrationContent_regulamin: "terms and conditions",
    tournament_tournamentRegistrationContent_zarejestrujSie: "SIGN UP",
    tournament_tournamentRegistrationContent_pomyslnieUtworzono: "Registration for the competition has been successfully created. To complete your registration and pay entry fee or to cancel - go to the tab",
    tournament_tournamentRegistrationContent_mojeKonto2: "MY ACCOUNT",
    tournament_tournamentRegistrationContent_lubKliknijPrzyciskPonizej: "or click the button below.",
    tournament_tournamentRegistrationContent_oplacUdzial: "PAY UP",
    tournament_tournamentRegistrationContent_pomyslnieZarejestrowanoNaZawody: "You have successfully registered for the competition. If you wish to make changes to your registration or cancel it, please go to the tab",
    tournament_tournamentRegistrationContent_mojeKonto3: "MY ACCOUNT",
    tournament_tournamentRegistrationContent_rejestracjaRozpocznieSie: "Registration will start",
    tournament_tournamentRegistrationContent_abyZarejestrowacSie: "To register for the competition you must first",
    tournament_tournamentRegistrationContent_zalogowac: "SIGN IN",
    //components > organisms > Tournament > TournamentRequirementsContent.js
    tournament_tournamentRequirementsContent_wymaganiaRejestracyjne: "Registration requirements:",
    //components > organisms > Tournament > TournamentStartContent.js
    tournament_tournamentRequirementsContent_wynikiLive: "LIVE RESULTS",
    //components > organisms > Tournament > TournamentElement.js
    tournament_tournamentElement_informacjeWkrotce: "Information soon",
    tournament_tournamentElement_brakDanych: "<No data>",
    tournament_tournamentElement_rejestracja: "Registration",
    tournament_tournamentElement_start: "start",
    tournament_tournamentElement_koniec: "end",
    tournament_tournamentElement_zakonczona: "completed",
    tournament_tournamentElement_konkurencje: "Events:",
    tournament_tournamentElement_informacjeWkrotce2: "Information soon",
    tournament_tournamentElement_brakDanych2: "<No data>",
    tournament_tournamentElement_wiecejInformacji: "Read more",
    //components > organisms > UserPanel > ScriptContent.js
    userPanel_scriptContent_konkurencja: "EVENT",
    userPanel_scriptContent_ukl: "COMP",
    userPanel_scriptContent_ukladanie: "COMPETING",
    userPanel_scriptContent_miesz: "SCR",
    userPanel_scriptContent_mieszanie: "SCRAMBLING",
    userPanel_scriptContent_bieg: "RUN",
    userPanel_scriptContent_bieganie: "RUNNING",
    userPanel_scriptContent_sedz: "JUDGE",
    userPanel_scriptContent_sedziowanie: "JUDGE",
    //components > organisms > UserPanel > UserEditPanel.js
    userPanel_userEditPanel_avatarNieZostalJeszcze: "Avatar has not been uploaded yet",
    userPanel_userEditPanel_brakZmian: "No changes",
    userPanel_userEditPanel_zapisano: "Saved",
    userPanel_userEditPanel_bladZapisu: "Writing error",
    userPanel_userEditPanel_wprowadzoneHasloJestNie: "The password you entered is incorrect",
    userPanel_userEditPanel_daneZostanaUtracone: "The data will be lost when you leave the page",
    userPanel_userEditPanel_ustawAwatar: "Set up an avatar",
    userPanel_userEditPanel_zanimPrzesleszZdjecie: "Before you upload a photo",
    userPanel_userEditPanel_list1: "1. You must be in the photo.",
    userPanel_userEditPanel_list2: "2. Only one face should be visible in the photo.",
    userPanel_userEditPanel_list3: "3. Unethical images or offensive content is not allowed.",
    userPanel_userEditPanel_list4: "4. The photo must follow general netiquette.",
    userPanel_userEditPanel_list5: "5. An account may be deleted for an incorrect photo.",
    userPanel_userEditPanel_akceptuje: "Accept",
    userPanel_userEditPanel_firstnameTitle: "Name",
    userPanel_userEditPanel_lastnameTitle: "Surname",
    userPanel_userEditPanel_dateTitle: "Date of birth",
    userPanel_userEditPanel_countryTitle: "Country",
    userPanel_userEditPanel_phoneTitle: "Phone",
    userPanel_userEditPanel_genderTitle: "Gender",
    userPanel_userEditPanel_miejscowoscTitle: "City",
    userPanel_userEditPanel_wcaIDTitle: "WCA ID",
    userPanel_userEditPanel_wcaIDAnnotation: "If you do not have your ID, leave this field blank",
    userPanel_userEditPanel_ostrzezeniePodane: "Warning! The information provided does not match your WCA account. If you think everything is correct, please continue.",
    userPanel_userEditPanel_akceptuje2: "Accept",
    userPanel_userEditPanel_anuluj: "Cancel",
    userPanel_userEditPanel_mojeDomyslneKonkurencje: "My default events",
    userPanel_userEditPanel_rozmiarKoszulkiTitle: "T-shirt size",
    userPanel_userEditPanel_zapisz: "SAVE",
    userPanel_userEditPanel_zmienHaslo: "CHANGE PASSWORD",
    userPanel_userEditPanel_noweHaslo: "NEW PASSWORD",
    userPanel_userEditPanel_powtorzNoweHaslo: "REPEAT NEW PASSWORD",
    userPanel_userEditPanel_stareHaslo: "OLD PASSWORD",
    userPanel_userEditPanel_wystapilBlad: "An error has occurred",
    userPanel_userEditPanel_zmienHaslo2: "CHANGE PASSWORD",
    userPanel_userEditPanel_anuluj2: "CANCEL",
    userPanel_userEditPanel_hasloZostaloZmienione: "The password has been changed",
    userPanel_userEditPanel_gotowe: "DONE",
    //components > organisms > UserPanel > UserPanelTournament.js
    userPanel_userPanelTournament_wyniki: "RESULTS",
    userPanel_userPanelTournament_scenariusz: "SCENARIO",
    userPanel_userPanelTournament_zmienKonkurencje: "CHANGE EVENTS",
    userPanel_userPanelTournament_oplacUdzial: "PAYMENT",
    userPanel_userPanelTournament_zatwierdz: "SAVE",
    userPanel_userPanelTournament_zrezygnuj: "CANCEL",
    userPanel_userPanelTournament_data: "DATE:",
    userPanel_userPanelTournament_statusRejestracji: "REGISTRATION STATUS:",
    userPanel_userPanelTournament_listaRezerwowa: "RESERVE LIST",
    userPanel_userPanelTournament_zatwierdzony: "APPROVED",
    userPanel_userPanelTournament_oczekujacy: "AWAITING",
    userPanel_userPanelTournament_mojeKonkurencje: "MY EVENTS:",
    userPanel_userPanelTournament_czyNaPewnoChcesz: "Are you sure you want to quit?",
    userPanel_userPanelTournament_czyNaPewnoChceszZrezygnowacPotwierdzajac: "Are you sure you want to cancel? By confirming the cancellation, a refund of the registration fee will be ordered and your registration will be cancelled.",
    userPanel_userPanelTournament_czyNaPewnoChceszZrezygnowacPotwierdzajacLeczOplata: "Are you sure you want to cancel? By confirming your cancellation, your registration will be cancelled, but your registration fee will not be refunded due to the expired refund deadline.",
    userPanel_userPanelTournament_nie: "NO",
    userPanel_userPanelTournament_tak: "YES",
    userPanel_userPanelTournament_anuluj: "cancel",
    userPanel_userPanelTournament_zapisz: "save",
    //components > organisms > UserPanel > UserPanelTournamentResults.js
    //components > organisms > UserPanel > UserPanelTournamentResults.js -- title do kostek -- constants > competitions.js
    userPanel_userPanelTournamentResults_wczytywanie: "Loading...",
    userPanel_userPanelTournamentResults_miejsce: "PLACE",
    userPanel_userPanelTournamentResults_wyniki: "RESULTS",
    userPanel_userPanelTournamentResults_zamknij: "CLOSE",
    userPanel_userPanelTournamentResults_klasyfikacja: "CLASSIFICATION",
    userPanel_userPanelTournamentResults_wczytywanie2: "Loading...",
    //components > organisms > UserPanel > UserPanelTournamentScript.js
    userPanel_userPanelTournamentScript_id: "ID:",
    userPanel_userPanelTournamentScript_wcaID: "WCA ID:",
    userPanel_userPanelTournamentScript_zamknij: "CLOSE",
    //pages > Contact.js
    pages_contact_wiadomoscWyslana: "Message sent",
    //pages > ForgottenPassword.js
    pages_forgottenPassword_wpiszSwojEmail: "Enter your email",
    pages_forgottenPassword_zapomnialesHasla: "Forgot password?",
    pages_forgottenPassword_wpiszSwojAdresEmailAbyMoc: "Please enter your e-mail address in order to reset your password. A link to the reset form will be sent to the e-mail address you provide.",
    pages_forgottenPassword_resetuj: "Reset",
    pages_forgottenPassword_emailZostalWyslany: "Email has been sent",
    //pages > GallerySite.js
    pages_gallerySite_nacisnijIkoneSercaPrzyZdjeciu: "Click the heart icon next to a photo to add it to your favourites.",
    pages_gallerySite_wybierzZawodyZListyAby: "Select a competition from the list to see photos",
    pages_gallerySite_galeria: "GALLERY",
    pages_gallerySite_nacisnijIkoneSercaPrzyZdjeciuAbyDodac: "Click the heart icon next to a photo to add it to your favourites.",
    pages_gallerySite_wybierzZawodyZListyAbyZobaczycZdjecia: "Select a competition from the list to see photos",
    pages_gallerySite_bladWczytywania: "Loading error",
    pages_gallerySite_brakZdjecWGalerii: "The gallery is empty",
    //pages > ResetPassword.js
    pages_resetPassword_podajNoweHaslo: "Enter a new password:",
    pages_resetPassword_powtorzHaslo: "Repeat the password:",
    pages_resetPassword_resetuj: "Reset",
    pages_resetPassword_wystapilBladPodczasZmianyHasla: "Password change error",
    pages_resetPassword_hasloZostaloZmienione: "Password changed, redirecting...",
    //pages > Series.js
    pages_series_bladWczytywania: "Loading error...",
    pages_series_wczytywanie: "Loading...",
    //pages > ThankYouPage.js
    pages_thankYouPage_dziekujemyZaRejestracje: "Thank you for registering!",
    pages_thankYouPage_zweryfikujKontoPoprzez: "Verify your account via the link sent to your email address.",
    pages_thankYouPage_linkNieDotarl: "Link not received?",
    pages_thankYouPage_wyslijPonownie: "SEND AGAIN",
    pages_thankYouPage_wyslano: "Sent",
    pages_thankYouPage_bladPodczasWysylaniaWiadomosci: "Message sending error",
    pages_thankYouPage_kodBledu: "(error code:",
    pages_thankYouPage_wiadomośćZSerweraBackend: "message from the backend server:",
    //pages > Tournament.js
    pages_tournament_brakHarmonogramu: "No schedule",
    pages_tournament_informacje: "INFORMATION",
    pages_tournament_harmonogram: "SCHEDULE",
    pages_tournament_rejestracja: "REGISTRATION",
    pages_tournament_wyniki: "RESULTS",
    pages_tournament_zawodnicy: "COMPETITORS",
    pages_tournament_wymagania: "REQUIREMENTS",
    pages_tournament_informacjeDodatkowe: "ADDITIONAL INFORMATION",
    pages_tournament_bladWczytywania: "Loading error...",
    //pages > Tournaments.js
    pages_tournaments_zawody: "COMPETITION",
    pages_tournaments_minione: "past",
    pages_tournaments_bladLadowaniaListy: "List loading error",
    //pages > UserPanel.js
    pages_userPanel_daneZostanaUtraconePo: "The data will be lost when you leave the page",
    pages_userPanel_dziekujemyZaOplacenieUdzialu: "Thank you for paying the registration fee - your registration is now complete. See you at the competition!",
    pages_userPanel_pomyslnieZrezygnowanoZZawodow: "Resignation from the competition went successfully.",
    pages_userPanel_pomyslnieZrezygnowanoZZawodowZwrot: "Resignation from the competition went successfully. A refund of the registration fee was ordered.",
    pages_userPanel_nieUczestniczyszWZadnychZawodach: "You do not participate in any competitions",
    pages_userPanel_minione: "past",
    pages_userPanel_mojeKonto: "my account",
    pages_userPanel_mojeZawody: "my competitions",
    pages_userPanel_edytujDane: "edit profile",
    pages_userPanel_wylogujSie: "sign out",
    pages_userPanel_czyNaPewnoChceszSie: "Are you sure you want to log out?",
    pages_userPanel_nie: "no",
    pages_userPanel_tak: "yes",
    //pages > VerifyAccount.js
    pages_verifyAccount_weryfikowanie: "Verifying...",
    pages_verifyAccount_zweryfikowanoPomyslnie: "Successfully verified, redirecting...",
    pages_verifyAccount_bladWeryfikacji: "Verification error",
    pages_verifyAccount_serwerBackendZwrocilBlad: "The backend server returned an error",
    pages_verifyAccount_wiadomosc: "; message:"
}
