export const customLabels = {
    //constants > competitions.js
    const_competitions_222: "2x2x2 Cube",
	const_competitions_333: "3x3x3 Cube",
	const_competitions_444: "4x4x4 Cube",
	const_competitions_555: "5x5x5 Cube",
	const_competitions_666: "6x6x6 Cube",
	const_competitions_777: "7x7x7 Cube",
	const_competitions_333bf: "3x3x3 Blindfolded",
	const_competitions_333oh: "3x3x3 One-Handed",
	const_competitions_clock: "Clock",
    const_competitions_minx: "Megaminx",
    const_competitions_pyram: "Pyraminx",
    const_competitions_skewb: "Skewb",
	const_competitions_sq1: "Square-1",
	const_competitions_333fm: "3x3x3 Fewest Moves",
    const_competitions_444bf: "4x4x4 Blindfolded",
    const_competitions_555bf: "5x5x5 Blindfolded",
    const_competitions_333mbf: "3x3x3 Multi-Blind",
    //constants > registerValidationSchema.js
    const_registerValidationSchema_emailNiepoprawny: "Wrong email",
    const_registerValidationSchema_emailWymagany: "Email required",
    const_registerValidationSchema_podajPanstwo: "Select the country",
    const_registerValidationSchema_minLiczbaZnakow: "Minimum 8 charakters needed",
    const_registerValidationSchema_hasloWymagane: "Password required",
    const_registerValidationSchema_akceptujRegulamin: "Accept the regulations",
    //constants > resetPasswordValidationSchema.js
    const_resetPasswordValidationSchema_minLiczbaZnakow: "Minimum 8 charakters needed",
    const_resetPasswordValidationSchema_podajNoweHaslo: "Enter a new password",
    const_resetPasswordValidationSchema_noweHasloMusi: "New password must be different",
    const_resetPasswordValidationSchema_haslaMuszaBycIdentyczne: "The passwords must be identical",
    const_resetPasswordValidationSchema_podajStareHaslo: "Enter the old password",
    //constants > userDataValidationSchema.js
    const_userDataValidationSchema_zaKrotkieImie: "Too short name",
    const_userDataValidationSchema_imieWymagane: "Name required",
    const_userDataValidationSchema_imieZawieraNiedozwoloneZnaki: "Name contains characters that are not allowed",
    const_userDataValidationSchema_dataWymagana: "Date required",
    const_userDataValidationSchema_minWiek: "Minimum age: 2 years",
    const_userDataValidationSchema_nieprawidlowy: "Incorrect",
    const_userDataValidationSchema_numerTelefonu: "Enter a phone number",
    const_userDataValidationSchema_nazwiskoWymagane: "Surname required",
    const_userDataValidationSchema_nazwiskoZawieraNiedozZnaki: "Surname contains characters that are not allowed",
    const_userDataValidationSchema_podajPlec: "Enter your gender",
    const_userDataValidationSchema_miastoWymagane: "City required",
    const_userDataValidationSchema_nieprawidlowy2: "Incorrect",
    const_userDataValidationSchema_uzytkownikOTakimWCA: "There is no such user ID at WCA",
    //constants > userProfileEditValidationSchema.js
    const_userProfileEditValidationSchema_podajPanstwo: "Enter the country",
    //components > molecules > Login > LoginButtonsWrapper.js
    login_loginButtonsWrapper_niePamietaszHasla: "Forgot your password?",
    //components > molecules > Login > LoginLeftWrapper.js
    login_loginLeftWrapper_nieMaszKonta: "No account?",
    //components > molecules > Register > InputWrapper.js
    register_inputWrapper_mezczyzna: "Male",
    register_inputWrapper_kobieta: "Female",
    register_inputWrapper_inna: "Other",
    //components > molecules > Register > RegisterCompetitions.js -- labelki brać z constants > competitions.js
    //components > molecules > Register > SelectSize.js
    register_selectSize_brak: "None",
    //components > molecules > Results > MenuItemRound.js
    results_menuItemRound_finaly: "Finals",
    results_menuItemRound_polfinaly: "Semifinals",
    results_menuItemRound_rundy: "Rounds",
    //components > molecules > Series > IconsMobileResults.js
    series_iconsMobileResults_bonus: "Extras",
    //components > molecules > Series > SeriesResultsIcon.js -- labelki brać z constants > competitions.js
    //components > molecules > Tournament > PlayerElement.js
    tournament_playerElement_zawodnik: "competitor",
    tournament_playerElement_zawodnik2: "competitor2",
    tournament_playerElement_miejscowosc: "City",
    tournament_playerElement_konkurencje: "events",
    //components > molecules > Tournament > SummaryPlayers.js
    tournament_summaryPlayers_liczbaZawodnikow: "Number of competitors",
    //components > molecules > Tournament > SummaryPlayersCube.js -- labelki brać z constants > competitions.js
    //components > molecules > Tournaments > SeriesButton.js
    tournaments_seriesButton_zawody: "Competitions",
    tournaments_seriesButton_serie: "Series",
    //components > molecules > Tournaments > TournamentsCompetitions.js -- labelki brać z constants > competitions.js
    //components > organisms > Organisms > ChangeLanguage.js
    changeLanguage_changeLanguage_en: "EN",
    //components > organisms > Contact > ContactForm.js
    contact_contactForm_zaKrotkiTytul: "Title too short",
    contact_contactForm_tytulWymagany: "Title required",
    contact_contactForm_emailNiepoprawny: "Email invalid",
    contact_contactForm_emailWymagany: "Email required",
    contact_contactForm_minimum10znakow: "10 characters minimum",
    contact_contactForm_wiadomoscWymagana: "Message required",
    contact_contactForm_napisz: "Write to us",
    contact_contactForm_emailTitle: "Your e-mail address",
    contact_contactForm_titleTitle: "Title",
    contact_contactForm_napiszWiadomosc: "Write a message",
    contact_contactForm_wyslij: "Send",
    //components > organisms > Contact > LeftWrapper.js
    contact_leftWrapper_zadzwon: "Phone",
    contact_leftWrapper_dolaczDoSerwera: "JOIN THE SERVER",
    //components > organisms > CookiesPopUp > CookiesPopUp.js
    cookiesPopUp_cookiesPopUp_korzystajacZNaszej: "By using our site, you consent to our use of cookies. You can set conditions for storing or accessing cookies in your browser.",
    //components > organisms > Gallery > GalleryMenu.js
    gallery_galleryMenu_ulubione: "FAVORITE",
    gallery_galleryMenu_ulubione2: "FAVORITE",
    gallery_galleryMenu_wybierzZawody: "SELECT COMPETITIONS",
    //components > organisms > Home > HomePageCardContact.js
    home_homePageCardContact_kontakt: "CONTACT",
    //components > organisms > Home > HomePageCardGallery.js
    home_homePageCardGallery_galeria: "GALLERY",
    //components > organisms > Home > HomePageCardTournaments.js
    home_homePageCardTournaments_zawody: "COMPETITIONS",
    //components > organisms > Home > HomePageCardTraining.js
    home_homePageCardTournaments_treningi: "TRAININGS",
    //components > organisms > Login > LoginForm.js
    login_loginForm_niepoprawnyEmail: "Incorrect E-mail",
    login_loginForm_emailWymagany: "E-mail required",
    login_loginForm_zaKrotkieHaslo: "Too short a password",
    login_loginForm_hasloWymagane: "Password required",
    login_loginForm_serwerOtrzymal: "The server received an invalid request",
    login_loginForm_uzytkownikJestJuzZalogowany: "The user is already logged in",
    login_loginForm_bladLogowania: "Login error",
    login_loginForm_bladLogowania2: "Login error",
    login_loginForm_zalogujSie: "Sign in",
    login_loginForm_emailPlaceholder: "E-MAIL",
    login_loginForm_passwordPlaceholder: "PASSWORD",
    //components > organisms > LoginLink > LoginLink.js
    loginLink_loginLink_mojeKonto: "MY ACCOUNT",
    loginLink_loginLink_zalogujSie: "SIGN IN",
    //components > organisms > payments > PaymentsPopup.js
    payments_paymentsPopup_zamknij: "CLOSE",
    //components > organisms > register > RegisterForm.js
    register_registerForm_adresieEmail: "e-mail address",
    register_registerForm_uzytkownikOPodanym: "User with",
    register_registerForm_juzIstnieje: "already exists",
    register_registerForm_ograniczenie: "Limit",
    register_registerForm_nieSpelnioneWBazie: "not met in the database",
    register_registerForm_nieznanyBladZapisu: "Unknown database write error",
    register_registerForm_nieznanyBlad: "Unknown error",
    register_registerForm_zarejestrujSie: "SIGN UP",
    register_registerForm_ustawAwatar: "Set your avatar",
    register_registerForm_zanimPrzesleszZdjecie: "Before you upload a photo",
    register_registerForm_list1: "1. You must be in the photo.",
    register_registerForm_list2: "2. Only one face should be visible in the photo.",
    register_registerForm_list3: "3. Unethical images or offensive content is not allowed.",
    register_registerForm_list4: "4. The photo must follow general netiquette.",
    register_registerForm_list5: "5. An account may be deleted for an incorrect photo.",
    register_registerForm_akceptuje: "Accept",
    register_registerForm_firstnameTitle: "Name",
    register_registerForm_lastnameTitle: "Surname",
    register_registerForm_emailTitle: "Email",
    register_registerForm_passwordTitle: "Password",
    register_registerForm_dateTitle: "Date of birth",
    register_registerForm_plecTitle: "Gender",
    register_registerForm_panstwoTitle: "Country",
    register_registerForm_miejscowoscTitle: "City",
    register_registerForm_numertelefonuTitle: "Phone number",
    register_registerForm_wcaidTitle: "WCA ID",
    register_registerForm_wcaidAnnotation: "If you do not have your ID, leave this field blank",
    register_registerForm_ostrzezenie: "Warning! The information provided does not match your WCA account. If you think everything is correct, please continue.",
    register_registerForm_akceptuje2: "Accept",
    register_registerForm_anuluj: "Cancel",
    register_registerForm_ustawSwojeDomyslne: "Set your default competitions",
    register_registerForm_domyslnyRozmiarKoszulki: "Default T-shirt size",
    register_registerForm_akceptuje3: "*I accept the",
    register_registerForm_regulamin: "terms and conditions",
    register_registerForm_wRegularminieZnajduje: "Please refer to the terms and conditions for the privacy policy, RODO regulations, and site rules.",
    register_registerForm_wyrazamZgodeNa: "I agree to receive the newsletter",
    register_registerForm_bladRejestracji: "Registration error",
    //components > organisms > results > ResultsData.js
    results_resultsData_konkurencja: "Event",
    results_resultsData_runda: "Round",
    results_resultsData_kategoria: "Category",
    //components > organisms > Series > SeriesMenu.js
    series_seriesMenu_serie: "Series",
    //components > organisms > Series > SeriesResults.js
    series_seriesResults_klasyfikacja: "Classification",
    series_seriesResults_wybierzZawodyZListy: "Select a competition from the list to view the classification",
    //components > organisms > Series > SeriesResultsElement.js
    series_seriesResultsElement_bonus: "extras",
    //components > organisms > Series > SeriesResultsElementHeading.js
    series_seriesResultsElementHeading_zawodnik: "Competitor",
    series_seriesResultsElementHeading_bonus: "Extras",
    series_seriesResultsElementHeading_sumaPunktow: "Total score",
    //components > organisms > Series > SeriesResultsMobileElement.js
    series_seriesResultsMobileElement_sumaPunktow: "Total score",
    //components > organisms > Tournament > TournamentInformationContent.js
    tournament_tournamentInformationContent_data: "Date",
    tournament_tournamentInformationContent_miejsce: "City",
    tournament_tournamentInformationContent_konkurencje: "Events",
    tournament_tournamentInformationContent_organizatorzy: "Organizers",
    tournament_tournamentInformationContent_delegaciWca: "WCA Delegates",
    tournament_tournamentInformationContent_limitZawodnikow: "Competitor limit",
    tournament_tournamentInformationContent_brakDanych: "<No data>",
    tournament_tournamentInformationContent_wpisowe: "entry fee",
    tournament_tournamentInformationContent_pln: "PLN",
    tournament_tournamentInformationContent_ostatecznyTerminZawarcia: "Limit date for refunds:",
    tournament_tournamentInformationContent_rejestracja: "Registration",
    tournament_tournamentInformationContent_ostatecznyTerminAkceptowania: "Deadline for accepting competitors from the waiting list:",
    tournament_tournamentInformationContent_ostatecznyTerminZmianyKonkurencji: "Deadline for competitors to update their registered events:",
    //components > organisms > Tournament > TournamentPlayersContent.js
    tournament_tournamentPlayersContent_rejestracjaNaZawody: "Registration for the event has not yet begun. To see the list of competitors, please come back here after registration has started 🙂",
    tournament_tournamentPlayersContent_listaRezerwowa: "RESERVE LIST",
    tournament_tournamentPlayersContent_listaOczekujacych: "WAITLIST",
    tournament_tournamentPlayersContent_obecnieNieMaZadnego: "There are currently no registered competitors",
    //components > organisms > Tournament > TournamentRegistrationContent.js
    tournament_tournamentRegistrationContent_bladWczytywania: "Loading error",
    tournament_tournamentRegistrationContent_wczytywanie: "Loading...",
    tournament_tournamentRegistrationContent_jestesJuzZarejestrowany: "You are already registered. If you wish to make changes to your registration or cancel it, please go to the tab",
    tournament_tournamentRegistrationContent_mojeKonto: "MY ACCOUNT",
    tournament_tournamentRegistrationContent_imieINazwisko: "Name and surname",
    tournament_tournamentRegistrationContent_plec: "Gender",
    tournament_tournamentRegistrationContent_adresEmail: "E-mail address",
    tournament_tournamentRegistrationContent_wcaID: "WCA ID",
    tournament_tournamentRegistrationContent_dataUrodzenia: "Date of birth",
    tournament_tournamentRegistrationContent_miejscowosc: "City",
    tournament_tournamentRegistrationContent_numerTelefonu: "phone",
    tournament_tournamentRegistrationContent_edytujDane: "EDIT PROFILE",
    tournament_tournamentRegistrationContent_zaznaczConajmniejJednaKonkurencje: "Select at least one competition",
    tournament_tournamentRegistrationContent_akceptujRegulamin: "Accept terms and conditions",
    tournament_tournamentRegistrationContent_wyborKonkurencji: "select events:",
    tournament_tournamentRegistrationContent_rozmiarKoszulkiTitle: "T-shirt size",
    tournament_tournamentRegistrationContent_akceptuje: "Accept",
    tournament_tournamentRegistrationContent_regulamin: "regulamin",
    tournament_tournamentRegistrationContent_zarejestrujSie: "ZAREJESTRUJ SIĘ",
    tournament_tournamentRegistrationContent_pomyslnieUtworzono: "Pomyślnie utworzono rejestrację na zawody. Aby dokończyć rejestrację i opłacić swój udział w zawodach lub zrezygnować, przejdź do zakładki",
    tournament_tournamentRegistrationContent_mojeKonto2: "MOJE KONTO",
    tournament_tournamentRegistrationContent_lubKliknijPrzyciskPonizej: "lub kliknij przycisk poniżej.",
    tournament_tournamentRegistrationContent_oplacUdzial: "OPŁAĆ UDZIAŁ",
    tournament_tournamentRegistrationContent_pomyslnieZarejestrowanoNaZawody: "Pomyślnie zarejestrowano na zawody. Jeśli chcesz dokonać zmian w swoim zgłoszeniu lub zrezygnować, przejdź do zakładki",
    tournament_tournamentRegistrationContent_mojeKonto3: "MOJE KONTO",
    tournament_tournamentRegistrationContent_rejestracjaRozpocznieSie: "Rejestracja rozpocznie się",
    tournament_tournamentRegistrationContent_abyZarejestrowacSie: "Aby zarejestrować się na zawody musisz się najpierw",
    tournament_tournamentRegistrationContent_zalogowac: "ZALOGOWAĆ",
    //components > organisms > Tournament > TournamentRequirementsContent.js
    tournament_tournamentRequirementsContent_wymaganiaRejestracyjne: "Wymagania rejestracyjne:",
    //components > organisms > Tournament > TournamentStartContent.js
    tournament_tournamentRequirementsContent_wynikiLive: "WYNIKI LIVE",
    //components > organisms > Tournament > TournamentElement.js
    tournament_tournamentElement_informacjeWkrotce: "Informacje wkrótce",
    tournament_tournamentElement_brakDanych: "<Brak danych>",
    tournament_tournamentElement_rejestracja: "Rejestracja",
    tournament_tournamentElement_start: "start",
    tournament_tournamentElement_koniec: "koniec",
    tournament_tournamentElement_zakonczona: "zakończona",
    tournament_tournamentElement_konkurencje: "Konkrencje:",
    tournament_tournamentElement_informacjeWkrotce2: "Informacje wkrótce",
    tournament_tournamentElement_brakDanych2: "<Brak danych>",
    tournament_tournamentElement_wiecejInformacji: "Więcej informacji",
    //components > organisms > UserPanel > ScriptContent.js
    userPanel_scriptContent_konkurencja: "KONKURENCJA",
    userPanel_scriptContent_ukl: "UKŁ.",
    userPanel_scriptContent_ukladanie: "UKŁADANIE",
    userPanel_scriptContent_miesz: "MIESZ.",
    userPanel_scriptContent_mieszanie: "MIESZANIE",
    userPanel_scriptContent_bieg: "BIEG.",
    userPanel_scriptContent_bieganie: "BIEGANIE",
    userPanel_scriptContent_sedz: "SĘDZ.",
    userPanel_scriptContent_sedziowanie: "SĘDZIOWANIE",
    //components > organisms > UserPanel > UserEditPanel.js
    userPanel_userEditPanel_avatarNieZostalJeszcze: "Avatar nie został jeszcze przesłany",
    userPanel_userEditPanel_brakZmian: "Brak zmian",
    userPanel_userEditPanel_zapisano: "Zapisano",
    userPanel_userEditPanel_bladZapisu: "Błąd zapisu",
    userPanel_userEditPanel_wprowadzoneHasloJestNie: "Wprowadzone hasło jest nieprawidłowe",
    userPanel_userEditPanel_daneZostanaUtracone: "Dane zostaną utracone po opuszczeniu strony",
    userPanel_userEditPanel_ustawAwatar: "Ustaw awatar",
    userPanel_userEditPanel_zanimPrzesleszZdjecie: "userPanel_userEditPanel_",
    userPanel_userEditPanel_list1: "1. Na zdjęciu musisz być Ty.",
    userPanel_userEditPanel_list2: "2. Na zdjęciu powinna być widoczna tylko jedna twarz.",
    userPanel_userEditPanel_list3: "3. Nieetyczne obrazki lub obraźliwe treści nie są dozwolone.",
    userPanel_userEditPanel_list4: "4. Zdjęcie musi być zgodne z ogólną netykietą.",
    userPanel_userEditPanel_list5: "5. Za nieprawidłowe zdjęcie konto może zostać permanentnie usunięte.",
    userPanel_userEditPanel_akceptuje: "Akceptuję",
    userPanel_userEditPanel_firstnameTitle: "Imię",
    userPanel_userEditPanel_lastnameTitle: "Nazwisko",
    userPanel_userEditPanel_dateTitle: "Data urodzenia",
    userPanel_userEditPanel_countryTitle: "Państwo",
    userPanel_userEditPanel_phoneTitle: "Telefon",
    userPanel_userEditPanel_genderTitle: "Płeć",
    userPanel_userEditPanel_miejscowoscTitle: "Miejscowość",
    userPanel_userEditPanel_wcaIDTitle: "WCA ID",
    userPanel_userEditPanel_wcaIDAnnotation: "Jeśli nie posiadasz swojego ID, pozostaw to pole puste",
    userPanel_userEditPanel_ostrzezeniePodane: "Ostrzeżenie! Podane dane nie zgadzają się z kontem WCA. Jeśli uważasz, że wszystko jest dobrze, przejdź dalej.",
    userPanel_userEditPanel_akceptuje2: "Akcpetuję",
    userPanel_userEditPanel_anuluj: "Anuluj",
    userPanel_userEditPanel_mojeDomyslneKonkurencje: "Moje domyślne konkurencje",
    userPanel_userEditPanel_rozmiarKoszulkiTitle: "Rozmiar koszulki",
    userPanel_userEditPanel_zapisz: "ZAPISZ",
    userPanel_userEditPanel_zmienHaslo: "ZMIEŃ HASŁO",
    userPanel_userEditPanel_noweHaslo: "NOWE HASŁO",
    userPanel_userEditPanel_powtorzNoweHaslo: "POWTÓRZ NOWE HASŁO",
    userPanel_userEditPanel_stareHaslo: "STARE HASŁO",
    userPanel_userEditPanel_wystapilBlad: "Wystąpił błąd",
    userPanel_userEditPanel_zmienHaslo2: "ZMIEŃ HASŁO",
    userPanel_userEditPanel_anuluj2: "ANULUJ",
    userPanel_userEditPanel_hasloZostaloZmienione: "Hasło zostało zmienione",
    userPanel_userEditPanel_gotowe: "GOTOWE",
    //components > organisms > UserPanel > UserPanelTournament.js
    userPanel_userPanelTournament_wyniki: "WYNIKI",
    userPanel_userPanelTournament_scenariusz: "SCENARIUSZ",
    userPanel_userPanelTournament_zmienKonkurencje: "ZMIEŃ KONKURENCJE",
    userPanel_userPanelTournament_oplacUdzial: "OPLAĆ UDZIAŁ",
    userPanel_userPanelTournament_zatwierdz: "ZATWIERDŹ",
    userPanel_userPanelTournament_zrezygnuj: "ZREZYGNUJ",
    userPanel_userPanelTournament_data: "DATA:",
    userPanel_userPanelTournament_statusRejestracji: "STATUS REJESTRACJI:",
    userPanel_userPanelTournament_listaRezerwowa: "LISTA REZERWOWA",
    userPanel_userPanelTournament_zatwierdzony: "ZATWIERDZONY",
    userPanel_userPanelTournament_oczekujacy: "OCZEKUJĄCY",
    userPanel_userPanelTournament_mojeKonkurencje: "MOJE KONKURENCJE:",
    userPanel_userPanelTournament_czyNaPewnoChcesz: "Czy na pewno chesz zrezygnować?",
    userPanel_userPanelTournament_czyNaPewnoChceszZrezygnowacPotwierdzajac: "Czy na pewno chcesz zrezygnować? Potwierdzając rezygnację zostanie zlecony zwrot opłaty wpisowej oraz Twoja rejestracja zostanie anulowana.",
    userPanel_userPanelTournament_czyNaPewnoChceszZrezygnowacPotwierdzajacLeczOplata: "Czy na pewno chcesz zrezygnować? Potwierdzając rezygnację Twoja rejestracja zostanie anulowana, lecz opłata wpisowa nie zostanie zwrócona ze względu na przekroczony czas ostatecznego terminu zwracania płatności.",
    userPanel_userPanelTournament_nie: "NIE",
    userPanel_userPanelTournament_tak: "TAK",
    userPanel_userPanelTournament_anuluj: "anuluj",
    userPanel_userPanelTournament_zapisz: "zapisz",
    //components > organisms > UserPanel > UserPanelTournamentResults.js
    //components > organisms > UserPanel > UserPanelTournamentResults.js -- title do kostek -- constants > competitions.js
    userPanel_userPanelTournamentResults_wczytywanie: "Wczytywanie...",
    userPanel_userPanelTournamentResults_miejsce: "MIEJSCE",
    userPanel_userPanelTournamentResults_wyniki: "WYNIKI",
    userPanel_userPanelTournamentResults_zamknij: "ZAMKNIJ",
    userPanel_userPanelTournamentResults_klasyfikacja: "KLASYFIKACJA",
    userPanel_userPanelTournamentResults_wczytywanie2: "Wczytywanie...",
    //components > organisms > UserPanel > UserPanelTournamentScript.js
    userPanel_userPanelTournamentScript_id: "ID:",
    userPanel_userPanelTournamentScript_wcaID: "WCA ID:",
    userPanel_userPanelTournamentScript_zamknij: "ZAMKNIJ",
    //pages > Contact.js
    pages_contact_wiadomoscWyslana: "Wiadomość wysłana",
    //pages > ForgottenPassword.js
    pages_forgottenPassword_wpiszSwojEmail: "Wpisz swój e-mail",
    pages_forgottenPassword_zapomnialesHasla: "Zapomniałeś hasła?",
    pages_forgottenPassword_wpiszSwojAdresEmailAbyMoc: "Wpisz swój adres e-mail, aby móc zresetować hasło. Na podany e-mail zostasnie wysłany link do formularza resetującego.",
    pages_forgottenPassword_resetuj: "Resetuj",
    pages_forgottenPassword_emailZostalWyslany: "Email został wysłany",
    //pages > GallerySite.js
    pages_gallerySite_nacisnijIkoneSercaPrzyZdjeciu: "Naciśnij ikonę serca przy zdjęciu, aby dodać je do ulubionych.",
    pages_gallerySite_wybierzZawodyZListyAby: "Wybierz zawody z listy aby zobaczyć zdjęcia",
    pages_gallerySite_galeria: "GALERIA",
    pages_gallerySite_nacisnijIkoneSercaPrzyZdjeciuAbyDodac: "Naciśnij ikonę serca przy zdjęciu, aby dodać je do ulubionych.",
    pages_gallerySite_wybierzZawodyZListyAbyZobaczycZdjecia: "Wybierz zawody z listy aby zobaczyć zdjęcia",
    pages_gallerySite_bladWczytywania: "Błąd wczytywania",
    pages_gallerySite_brakZdjecWGalerii: "Brak zdjęć w galerii",
    //pages > ResetPassword.js
    pages_resetPassword_podajNoweHaslo: "Podaj nowe hasło:",
    pages_resetPassword_powtorzHaslo: "Powtórz hasło:",
    pages_resetPassword_resetuj: "Resetuj",
    pages_resetPassword_wystapilBladPodczasZmianyHasla: "Wystąpił błąd podczas zmiany hasła",
    pages_resetPassword_hasloZostaloZmienione: "Hasło zostało zmienione, przekierowywanie...",
    //pages > Series.js
    pages_series_bladWczytywania: "Błąd wczytywania...",
    pages_series_wczytywanie: "Wczytywanie...",
    //pages > ThankYouPage.js
    pages_thankYouPage_dziekujemyZaRejestracje: "Dziękujemy za rejestrację!",
    pages_thankYouPage_zweryfikujKontoPoprzez: "Zweryfikuj konto poprzez link wysłany na twoją skrzynkę email.",
    pages_thankYouPage_linkNieDotarl: "Link nie dotarł?",
    pages_thankYouPage_wyslijPonownie: "WYŚLIJ PONOWNIE",
    pages_thankYouPage_wyslano: "Wysłano",
    pages_thankYouPage_bladPodczasWysylaniaWiadomosci: "Błąd podczas wysyłania wiadomości",
    pages_thankYouPage_kodBledu: "(kod błędu:",
    pages_thankYouPage_wiadomośćZSerweraBackend: "wiadomość z serwera backend:",
    //pages > Tournament.js
    pages_tournament_brakHarmonogramu: "Brak harmonogramu",
    pages_tournament_informacje: "INFORMACJE",
    pages_tournament_harmonogram: "HARMONOGRAM",
    pages_tournament_rejestracja: "REJESTRACJA",
    pages_tournament_wyniki: "WYNIKI",
    pages_tournament_zawodnicy: "ZAWODNICY",
    pages_tournament_wymagania: "WYMAGANIA",
    pages_tournament_informacjeDodatkowe: "INFORMACJE DODATKOWE",
    pages_tournament_bladWczytywania: "Błąd wczytywania...",
    //pages > Tournaments.js
    pages_tournaments_zawody: "ZAWODY",
    pages_tournaments_minione: "minione",
    pages_tournaments_bladLadowaniaListy: "Błąd ładowania listy",
    //pages > UserPanel.js
    pages_userPanel_daneZostanaUtraconePo: "Dane zostaną utracone po opuszczeniu strony",
    pages_userPanel_dziekujemyZaOplacenieUdzialu: "Dziękujemy za opłacenie udziału - Twoja rejestracja jest już kompletna. Do zobaczenia na zawodach!",
    pages_userPanel_pomyslnieZrezygnowanoZZawodow: "Pomyślnie zrezygnowano z zawodów.",
    pages_userPanel_pomyslnieZrezygnowanoZZawodowZwrot: "Pomyślnie zrezygnowano z zawodów. Zwrot opłaty wpisowej został zlecony.",
    pages_userPanel_nieUczestniczyszWZadnychZawodach: "Nie uczestniczysz w żadnych zawodach",
    pages_userPanel_minione: "minione",
    pages_userPanel_mojeKonto: "moje konto",
    pages_userPanel_mojeZawody: "moje zawody",
    pages_userPanel_edytujDane: "edytuj dane",
    pages_userPanel_wylogujSie: "wyloguj sie",
    pages_userPanel_czyNaPewnoChceszSie: "czy na pewno chcesz się wylogować?",
    pages_userPanel_nie: "nie",
    pages_userPanel_tak: "tak",
    //pages > VerifyAccount.js
    pages_verifyAccount_weryfikowanie: "Weryfikowanie...",
    pages_verifyAccount_zweryfikowanoPomyslnie: "Zweryfikowano pomyślnie, przekierowywanie...",
    pages_verifyAccount_bladWeryfikacji: "Błąd weryfikacji",
    pages_verifyAccount_serwerBackendZwrocilBlad: "Serwer backend zwrócił błąd",
    pages_verifyAccount_wiadomosc: "; wiadomość:"
}